/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "hourly.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TimeStamp, TimeStamp, AUTO)


PB_BIND(TimeStamp_date, TimeStamp_date, AUTO)


PB_BIND(HourlyData, HourlyData, AUTO)


PB_BIND(HourlyData_readings, HourlyData_readings, AUTO)


PB_BIND(HourlyData_SensorBoard, HourlyData_SensorBoard, AUTO)


PB_BIND(HourlyData_EnvironmentalBoard, HourlyData_EnvironmentalBoard, AUTO)


PB_BIND(HourlyData_SystemEvents, HourlyData_SystemEvents, AUTO)




